config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root to: redirect('/articles')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.append('articles', @article) }
        format.html { redirect_to @article, notice: "Article was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: "Article was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: "Article was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<turbo-frame id="<%= dom_id article %>" class="scaffold_record">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>

  <p>
    <%= link_to "Edit this article", edit_article_path(article) %>
  </p>
</turbo-frame>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
    <input type="reset">
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<turbo-frame id="<%= dom_id @article %>">
<%= render "form", article: @article %>
<%= link_to "Cancel", @article, "data-turbo-action": "restore" %>
</turbo-frame>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Article</h1>

<div id="articles">
  <%= render @articles %>
</div>

<turbo-frame id="new_article" src="<%= new_article_path %>" target="_top">
  <%= link_to "New article", new_article_path %>
</turbo-frame>

app/views/articles/new.html.erb
<h1>New article</h1>

<turbo-frame id="new_article">
<%= render "form", article: @article %>
</turbo-frame>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", article_path(@article), method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7a2sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>